### PR TITLE
Restructure data in line chart, use PapaParse not d3

### LINKED ISSUE #1: consider revising how line-chart pulls in data
@ilyankou  - We can discuss this at our next meeting if you wish, but here are some thoughts. 

Please consider revising how line-chart pulls in data.csv. I'm happy to pay 1-2 hours to do this, if you think it makes sense.

Currently, data.csv is organized horizontally, with colors at the end, like this:

name, 2015, 2016, 2017, color
Hartford, 4444, 5555, 6666, blue

While this offers control over individual colors, that's not essential in my mind, because of the wonderful https://nagix.github.io/chartjs-plugin-colorschemes you inserted. My favorite is setting is brewer.SetOne9

Instead, I would prefer a vertical organization, with no colors, like this:
year   Hartford
2015  4444
2016  5555
2017  6666
...

Reasons:
- Most longitudinal data is already organized in vertical columns
- Data for other charts (such as scatter-chart) is organized vertically
- Some longitudinal data has many years/decades in the X-axis, so it's more efficient to pull this directly from data.csv rather than having to re-enter it into the script.js

### PR DESCRIPTION
**Pull request by ilyankou**
Resolve #1

### CODE REVIEW

**Comment by ilyankou** [comment]
See demo: https://ilyankou.github.io/chartjs-templates/line-chart/

Code: https://github.com/ilyankou/chartjs-templates/tree/master/line-chart 

I also fixed an issue: when you change width of browser window, the chart doesn't "explode" or shrink anymore, instead its height remains constant.

**Comment by JackDougherty** [comment]
thanks @ilyankou

**Comment by dnaneet** [comment]
My apologies for being a complete novice.  I am trying to learning ChartJS by example.  I downloaded your examples locally to my linux laptop.  None of the HTML files show the plot, when I load them. They are blank.  The only thing that does appear is the footnote that invites a user to download the data.

It seems that I may be making a novice error and I just do not know what it is.  **Is this something you can help with?**  Thank you.

**Comment by JackDougherty** [comment]
@dnaneet -- the chart.js code templates we currently use require users to upload them to a server. See Chapter 8: Modify and Host Code on GitHub in our book https://handsondataviz.org/github.html

**Comment by dnaneet** [comment]
> @dnaneet -- the chart.js code templates we currently use require users to upload them to a server. See Chapter 8: Modify and Host Code on GitHub in our book https://handsondataviz.org/github.html

Thank you for your prompt reply! I will check this out.  Good day!

**Pull request merged**
